language: python
python:
  - 2.6
  - 2.7
  - 3.2
notifications:
  email:
   - raphael.pinson@camptocamp.com
install:
  # Use latest Augeas
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install libaugeas-dev libxml2-dev
matrix:
  allow_failures:
    - python: 3.2
script: make && make check
